name = "itm-inventory-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "itm_inventory"
database_id = "af27ae08-96ff-4a45-95e1-a15404042808"